blank_issues_enabled: false
contact_links:
  - name: Google AI Gemini API
    url: https://github.com/google-gemini
    about: This repository is for [Generative AI with Vertex AI on Google Cloud](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/overview), not the [Google AI Gemini/PaLM APIs](https://ai.google.dev/). For issues with the Google AI Gemini API, refer to the [google-gemini](https://github.com/google-gemini) organization or the [Google Developers Community Discourse](https://discuss.ai.google.dev/).
  - name: Google Cloud Support
    url: https://cloud.google.com/support/
    about: If you have a support contract with Google, please create a case in the support console instead of filing on GitHub. This will ensure a timely response.
  - name: Stack Overflow - Google Cloud Collective
    url: https://stackoverflow.com/collectives/google-cloud
    about: A collective for developers who utilize Google Cloud's infrastructure and platform capabilities. This collective is organized and managed by the Stack Overflow community.
