name: Add labels to PRs

on:
  pull_request:
    types: opened
  push:
    branches:
      - action-label-owlbot-run  # Temporary for testing

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
