name: Label Forked Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
    label_pr:
        runs-on: ubuntu-latest
    
        steps:
        - name: Check if PR is from a fork
            id: check_fork
            if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
            run: echo "name=is_fork::true" >> $GITHUB_OUTPUT
        
        - name: Add label if from a fork
            if: steps.check_fork.outputs.is_fork == 'true'
            uses: actions/labeler@v3
            with:
            repo: ${{ github.repository }}
            pr_number: ${{ github.event.pull_request.number }}
            labels: owlbot:run
